import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import Heading from "@/components/Heading";
import MainNavBar from "@/components/MainNavBar";
import Footer from "@/components/Footer";

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Heading />
        <MainNavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
